apiVersion: v1
kind: Service
metadata:
  name: list-embedding-generator-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9090
      targetPort: 80
      protocol: TCP
  selector:
    app: list-embedding-generator
