apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: list-embedding-generator-stateful
  labels:
    app: list-embedding-generator
spec:
  serviceName: list-embedding-generator
  replicas: 1
  selector:
    matchLabels:
      app: list-embedding-generator
  template:
    metadata:
      labels:
        app: list-embedding-generator
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: list-embedding-generator
        image: ghcr.io/piaimarket-flow-finder/list-vectorizer:latest
        # If you build the image locally, change the next line to `imagePullPolicy: Never` - there is no need to pull the image
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        envFrom:
          - configMapRef:
              name: list-embedding-generator-config
